name: "XGBoostModel-Optuna"
model_class: "src.models.xgboost.XGBoostModel"

# Base parameters (will be overridden by Optuna for parameters in search space)
init_params:
  random_state: 42
  verbosity: 0

# Optuna configuration
optuna_config:
  enabled: true
  n_trials: 100
  optimize_metric: "rmse_val"  # Metric to minimize
  use_pruning: true
  n_startup_trials: 5
  n_warmup_steps: 1
  
  # XGBoost hyperparameter search space
  search_space:
    n_estimators:
      type: "int"
      low: 100
      high: 1000
      step: 50
    
    max_depth:
      type: "int"
      low: 3
      high: 10
    
    learning_rate:
      type: "float"
      low: 0.01
      high: 0.3
      log: true
    
    subsample:
      type: "float"
      low: 0.5
      high: 1.0
    
    colsample_bytree:
      type: "float"
      low: 0.5
      high: 1.0
    
    min_child_weight:
      type: "int"
      low: 1
      high: 10
    
    gamma:
      type: "float"
      low: 0.0
      high: 0.5
    
    reg_alpha:
      type: "float"
      low: 0.0
      high: 1.0
    
    reg_lambda:
      type: "float"
      low: 0.0
      high: 2.0